[package]
name = "wsd"
version = "0.0.2"
edition = "2021"
description = "Delivers what simply defined."
license = "MIT"
repository = "https://github.com/sweihub/wsd"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
